filter:
   excluded_paths: [vendor/*, tests/*]

before_commands:
    - 'composer install --prefer-source'

tools:
    external_code_coverage: true
    php_mess_detector: true
    sensiolabs_security_checker: true
    php_analyzer:
    	config:
        	doc_comment_fixes:
            	enabled: false
    php_code_coverage:
      enabled: true
      filter:
        excluded_paths: [vendor, tests]
    php_pdepend:
      enabled: true
      excluded_dirs:
        - vendor
        - tests
    php_loc:
        enabled: true
        excluded_dirs: [vendor, tests]
    php_cpd:
        enabled: true
        command: phpcpd
        excluded_dirs: [vendor, tests]
