filter:
  paths:  [src/*]
  excluded_paths: [vendor/*, tests/*]

before_commands:
  - "composer install --prefer-source"

tools:
  external_code_coverage: true
  php_mess_detector: true
  sensiolabs_security_checker: true
  php_code_coverage: true
  php_analyzer:
    config:
        verify_php_doc_comments:
          suggest_more_specific_types: false
  php_code_coverage:
    enabled: true
  php_cpd:
    enabled: true
    command: phpcpd
    excluded_dirs: [vendor, tests]
