filter:
  paths:  [src/*]
  excluded_paths: [vendor/*, tests/*]

before_commands:
  - 'composer install --prefer-source'

tools:
  external_code_coverage: true
  sensiolabs_security_checker: true
  php_code_coverage:
    enabled: true
  php_analyzer:
    config:
        verify_php_doc_comments:
          suggest_more_specific_types: false
