language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

install:
  - composer install --prefer-source

before_script:
  - if [ $TRAVIS_PHP_VERSION = '5.6' ]; then PHPUNIT_FLAGS="--coverage-clover=coverage.clover"; fi
  - if [ $TRAVIS_PHP_VERSION = '5.6' ]; then vendor/bin/phpcs src tests --standard=src/ZenifyCodingStandard/ruleset.xml --ignore=wrong,correct; fi

script:
  - phpunit $PHPUNIT_FLAGS

after_script:
  - if [ ! -z "$PHPUNIT_FLAGS" ]; then wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi
