language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

before_install:
  - composer self-update

install:
  - composer install --prefer-source

before_script:
  # php linter
  - vendor/bin/parallel-lint -e php --exclude vendor .
  # php copy/paste detector
  - vendor/bin/phpcpd src
  - vendor/bin/phpcpd tests
  # php code-sniffer
  - vendor/bin/phpcs src --standard=src/ZenifyCodingStandard/code-sniffer-ruleset.xml
  - vendor/bin/phpcs tests --extensions=phpt --standard=src/ZenifyCodingStandard/code-sniffer-ruleset.xml
  # php mess-detector
  - vendor/bin/phpmd src text src/ZenifyCodingStandard/mess-detector-ruleset.xml

script:
  - vendor/bin/phpunit --coverage-clover=coverage.clover

after_script:
  # move code coverage
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
