language: php

php:
  - 5.5
  - 5.6
  - hhvm

before_install:
  - composer self-update

install:
  - composer install --prefer-source

before_script:
  # php linter
  - vendor/bin/parallel-lint -e php src tests
  # php code-sniffer
  - vendor/bin/phpcs src tests/ZenifyTests --standard=src/ZenifyCodingStandard/ruleset.xml --ignore=wrong,correct,bootstrap
  # php mess-detector
  - vendor/bin/phpmd src,tests text src/ZenifyMessDetector/ruleset.xml --exclude "correct*,wrong*"

script:
  - vendor/bin/phpunit --coverage-clover=coverage.clover

after_script:
  # move code coverage
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
